# Site settings
title: A Journey Worth Taking
header-img: img/home-bg.png
email: adeel.a.mhd@gmail.com
copyright_name: AAM77
description: > # this means to ignore newlines until "baseurl:"
  Learning to Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AAM77
learn_profile: AAM77
email_username: adeel.a.mhd@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
